### ISSUE TITLE
Can't support color words's display(My english is poor )_)  )

### ISSUE THREAD

**Issue by KyleBing** [ggordan/GutterColor#86] opened 2015-08-26 00:47 UTC
![screen2015_0826_0842](https://cloud.githubusercontent.com/assets/12215982/9483114/afc507f0-4bce-11e5-860c-2430773603ac.jpg)

as the pictures shows, the color words can't show Color dot in the front.

**Comment by jbrooksuk** [comment] 2015-08-26 06:58
Duplicate of https://github.com/ggordan/GutterColor/issues/16

**Closed by jbrooksuk** 2015-08-26 06:58 UTC
