### ISSUE TITLE
Match incorrectly #defxyz

### ISSUE THREAD

**Issue by rexdf** [ggordan/GutterColor#81] opened 2015-04-09 14:15 UTC
`- ['Definition' Plugins](#definition-plugins)` or even more simple `#defxvbg` will has a color gutter.

**Comment by jbrooksuk** [comment] 2015-04-09 14:17
`#def` matches the hex code of three characters. It should be a stricter regex.

**Comment by jbrooksuk** [comment] 2015-04-09 14:19
Should be fixed up for you now.

**Comment by rexdf** [comment] 2015-04-09 14:51
Thx. So quickly.  But it seems to disable most of gutter color icons.  Maybe I should not depend on that it will work with markdown.

I try to color the css block in markdown. Compared to css/scss/sass, it's not important.

Maybe you should revert it. I'm not sure about it. But thing seem to be worse than before. It seems not work with css in `Gutter Color/test.css`.

**Comment by jbrooksuk** [comment] 2015-04-09 14:52
Ah crap. The problem is that the regex is now looking to have no characters after the last character in the hex code, obviously a `;` will follow. I'll revert the change.

**Closed** 2015-04-09 14:54 UTC
Labels: bug
